version: "3"

services:
  rexample:
    image: rexample
    build: ./R_example
    ports:
      - "8000:8000"
    networks:
      - network
    restart: on-failure


  py_example:
    image: pyexample
    build: ./Py_Example
    ports:
      - "5000:5000"
    networks:
      - network
    restart: on-failure

networks:
  network: {}
